package ch.enterag.utils.jdbc;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;


public abstract class BasePreparedStatement
        implements PreparedStatement {
    private PreparedStatement _pstmtWrapped = null;


    public BasePreparedStatement(PreparedStatement pstmtWrapped) throws SQLException {
        this._pstmtWrapped = pstmtWrapped;
        if (this._pstmtWrapped != null) {
            this._pstmtWrapped.setEscapeProcessing(false);
        }
    }


    public Connection getConnection() throws SQLException {
        return this._pstmtWrapped.getConnection();
    }


    public ResultSetMetaData getMetaData() throws SQLException {
        return this._pstmtWrapped.getMetaData();
    }


    public ParameterMetaData getParameterMetaData() throws SQLException {
        return this._pstmtWrapped.getParameterMetaData();
    }


    public ResultSet getResultSet() throws SQLException {
        return this._pstmtWrapped.getResultSet();
    }


    public void addBatch(String sql) throws SQLException {
        this._pstmtWrapped.addBatch(sql);
    }


    public void cancel() throws SQLException {
        this._pstmtWrapped.cancel();
    }


    public void clearBatch() throws SQLException {
        this._pstmtWrapped.clearBatch();
    }


    public void clearWarnings() throws SQLException {
        this._pstmtWrapped.clearWarnings();
    }


    public void close() throws SQLException {
        this._pstmtWrapped.close();
    }


    public void closeOnCompletion() throws SQLException {
        this._pstmtWrapped.closeOnCompletion();
    }


    public boolean execute(String sql) throws SQLException {
        return this._pstmtWrapped.execute(sql);
    }


    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return this._pstmtWrapped.execute(sql, autoGeneratedKeys);
    }


    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return this._pstmtWrapped.execute(sql, columnIndexes);
    }


    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return this._pstmtWrapped.execute(sql, columnNames);
    }


    public int[] executeBatch() throws SQLException {
        return this._pstmtWrapped.executeBatch();
    }


    public ResultSet executeQuery(String sql) throws SQLException {
        return this._pstmtWrapped.executeQuery(sql);
    }


    public int executeUpdate(String sql) throws SQLException {
        return this._pstmtWrapped.executeUpdate(sql);
    }


    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return this._pstmtWrapped.executeUpdate(sql, autoGeneratedKeys);
    }


    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return this._pstmtWrapped.executeUpdate(sql, columnIndexes);
    }


    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return this._pstmtWrapped.executeUpdate(sql, columnNames);
    }


    public int getFetchDirection() throws SQLException {
        return this._pstmtWrapped.getFetchDirection();
    }


    public int getFetchSize() throws SQLException {
        return this._pstmtWrapped.getFetchSize();
    }


    public ResultSet getGeneratedKeys() throws SQLException {
        return this._pstmtWrapped.getGeneratedKeys();
    }


    public int getMaxFieldSize() throws SQLException {
        return this._pstmtWrapped.getMaxFieldSize();
    }


    public int getMaxRows() throws SQLException {
        return this._pstmtWrapped.getMaxRows();
    }


    public boolean getMoreResults() throws SQLException {
        return this._pstmtWrapped.getMoreResults();
    }


    public boolean getMoreResults(int current) throws SQLException {
        return this._pstmtWrapped.getMoreResults(current);
    }


    public int getQueryTimeout() throws SQLException {
        return this._pstmtWrapped.getQueryTimeout();
    }


    public int getResultSetConcurrency() throws SQLException {
        return this._pstmtWrapped.getResultSetConcurrency();
    }


    public int getResultSetHoldability() throws SQLException {
        return this._pstmtWrapped.getResultSetHoldability();
    }


    public int getResultSetType() throws SQLException {
        return this._pstmtWrapped.getResultSetType();
    }


    public int getUpdateCount() throws SQLException {
        return this._pstmtWrapped.getUpdateCount();
    }


    public SQLWarning getWarnings() throws SQLException {
        return this._pstmtWrapped.getWarnings();
    }


    public boolean isCloseOnCompletion() throws SQLException {
        return this._pstmtWrapped.isCloseOnCompletion();
    }


    public boolean isClosed() throws SQLException {
        return this._pstmtWrapped.isClosed();
    }


    public boolean isPoolable() throws SQLException {
        return this._pstmtWrapped.isPoolable();
    }


    public void setCursorName(String name) throws SQLException {
        this._pstmtWrapped.setCursorName(name);
    }


    public void setEscapeProcessing(boolean enable) throws SQLException {
        this._pstmtWrapped.setEscapeProcessing(enable);
    }


    public void setFetchDirection(int direction) throws SQLException {
        this._pstmtWrapped.setFetchDirection(direction);
    }


    public void setFetchSize(int rows) throws SQLException {
        this._pstmtWrapped.setFetchSize(rows);
    }


    public void setMaxFieldSize(int max) throws SQLException {
        this._pstmtWrapped.setMaxFieldSize(max);
    }


    public void setMaxRows(int max) throws SQLException {
        this._pstmtWrapped.setMaxRows(max);
    }


    public void setPoolable(boolean poolable) throws SQLException {
        this._pstmtWrapped.setPoolable(poolable);
    }


    public void setQueryTimeout(int seconds) throws SQLException {
        this._pstmtWrapped.setQueryTimeout(seconds);
    }


    public void addBatch() throws SQLException {
        this._pstmtWrapped.addBatch();
    }


    public void clearParameters() throws SQLException {
        this._pstmtWrapped.clearParameters();
    }


    public boolean execute() throws SQLException {
        return this._pstmtWrapped.execute();
    }


    public ResultSet executeQuery() throws SQLException {
        return this._pstmtWrapped.executeQuery();
    }


    public int executeUpdate() throws SQLException {
        return this._pstmtWrapped.executeUpdate();
    }


    public void setArray(int parameterIndex, Array x) throws SQLException {
        this._pstmtWrapped.setArray(parameterIndex, x);
    }


    public void setAsciiStream(int parameterIndex, InputStream x) throws SQLException {
        this._pstmtWrapped.setAsciiStream(parameterIndex, x);
    }


    public void setAsciiStream(int parameterIndex, InputStream x, int length) throws SQLException {
        this._pstmtWrapped.setAsciiStream(parameterIndex, x, length);
    }


    public void setAsciiStream(int parameterIndex, InputStream x, long length) throws SQLException {
        this._pstmtWrapped.setAsciiStream(parameterIndex, x, length);
    }


    public void setBigDecimal(int parameterIndex, BigDecimal x) throws SQLException {
        this._pstmtWrapped.setBigDecimal(parameterIndex, x);
    }


    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        this._pstmtWrapped.setBinaryStream(parameterIndex, x);
    }


    public void setBinaryStream(int parameterIndex, InputStream x, int length) throws SQLException {
        this._pstmtWrapped.setBinaryStream(parameterIndex, x, length);
    }


    public void setBinaryStream(int parameterIndex, InputStream x, long length) throws SQLException {
        this._pstmtWrapped.setBinaryStream(parameterIndex, x, length);
    }


    public void setBlob(int parameterIndex, Blob x) throws SQLException {
        this._pstmtWrapped.setBlob(parameterIndex, x);
    }


    public void setBlob(int parameterIndex, InputStream inputStream) throws SQLException {
        this._pstmtWrapped.setBlob(parameterIndex, inputStream);
    }


    public void setBlob(int parameterIndex, InputStream inputStream, long length) throws SQLException {
        this._pstmtWrapped.setBlob(parameterIndex, inputStream, length);
    }


    public void setBoolean(int parameterIndex, boolean x) throws SQLException {
        this._pstmtWrapped.setBoolean(parameterIndex, x);
    }


    public void setByte(int parameterIndex, byte x) throws SQLException {
        this._pstmtWrapped.setByte(parameterIndex, x);
    }


    public void setBytes(int parameterIndex, byte[] x) throws SQLException {
        this._pstmtWrapped.setBytes(parameterIndex, x);
    }


    public void setCharacterStream(int parameterIndex, Reader reader) throws SQLException {
        this._pstmtWrapped.setCharacterStream(parameterIndex, reader);
    }


    public void setCharacterStream(int parameterIndex, Reader reader, int length) throws SQLException {
        this._pstmtWrapped.setCharacterStream(parameterIndex, reader, length);
    }


    public void setCharacterStream(int parameterIndex, Reader reader, long length) throws SQLException {
        this._pstmtWrapped.setCharacterStream(parameterIndex, reader, length);
    }


    public void setClob(int parameterIndex, Clob x) throws SQLException {
        this._pstmtWrapped.setClob(parameterIndex, x);
    }


    public void setClob(int parameterIndex, Reader reader) throws SQLException {
        this._pstmtWrapped.setClob(parameterIndex, reader);
    }


    public void setClob(int parameterIndex, Reader reader, long length) throws SQLException {
        this._pstmtWrapped.setClob(parameterIndex, reader, length);
    }


    public void setDate(int parameterIndex, Date x) throws SQLException {
        this._pstmtWrapped.setDate(parameterIndex, x);
    }


    public void setDate(int parameterIndex, Date x, Calendar cal) throws SQLException {
        this._pstmtWrapped.setDate(parameterIndex, x, cal);
    }


    public void setDouble(int parameterIndex, double x) throws SQLException {
        this._pstmtWrapped.setDouble(parameterIndex, x);
    }


    public void setFloat(int parameterIndex, float x) throws SQLException {
        this._pstmtWrapped.setFloat(parameterIndex, x);
    }


    public void setInt(int parameterIndex, int x) throws SQLException {
        this._pstmtWrapped.setInt(parameterIndex, x);
    }


    public void setLong(int parameterIndex, long x) throws SQLException {
        this._pstmtWrapped.setLong(parameterIndex, x);
    }


    public void setNCharacterStream(int parameterIndex, Reader value) throws SQLException {
        this._pstmtWrapped.setNCharacterStream(parameterIndex, value);
    }


    public void setNCharacterStream(int parameterIndex, Reader value, long length) throws SQLException {
        this._pstmtWrapped.setNCharacterStream(parameterIndex, value, length);
    }


    public void setNClob(int parameterIndex, NClob value) throws SQLException {
        this._pstmtWrapped.setNClob(parameterIndex, value);
    }


    public void setNClob(int parameterIndex, Reader reader) throws SQLException {
        this._pstmtWrapped.setNClob(parameterIndex, reader);
    }


    public void setNClob(int parameterIndex, Reader reader, long length) throws SQLException {
        this._pstmtWrapped.setNClob(parameterIndex, reader, length);
    }


    public void setNString(int parameterIndex, String value) throws SQLException {
        this._pstmtWrapped.setNString(parameterIndex, value);
    }


    public void setNull(int parameterIndex, int sqlType) throws SQLException {
        this._pstmtWrapped.setNull(parameterIndex, sqlType);
    }


    public void setNull(int parameterIndex, int sqlType, String typeName) throws SQLException {
        this._pstmtWrapped.setNull(parameterIndex, sqlType, typeName);
    }


    public void setObject(int parameterIndex, Object x) throws SQLException {
        this._pstmtWrapped.setObject(parameterIndex, x);
    }


    public void setObject(int parameterIndex, Object x, int targetSqlType) throws SQLException {
        this._pstmtWrapped.setObject(parameterIndex, x, targetSqlType);
    }


    public void setObject(int parameterIndex, Object x, int targetSqlType, int scaleOrLength) throws SQLException {
        this._pstmtWrapped.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
    }


    public void setRef(int parameterIndex, Ref x) throws SQLException {
        this._pstmtWrapped.setRef(parameterIndex, x);
    }


    public void setRowId(int parameterIndex, RowId x) throws SQLException {
        this._pstmtWrapped.setRowId(parameterIndex, x);
    }


    public void setSQLXML(int parameterIndex, SQLXML xmlObject) throws SQLException {
        this._pstmtWrapped.setSQLXML(parameterIndex, xmlObject);
    }


    public void setShort(int parameterIndex, short x) throws SQLException {
        this._pstmtWrapped.setShort(parameterIndex, x);
    }


    public void setString(int parameterIndex, String x) throws SQLException {
        this._pstmtWrapped.setString(parameterIndex, x);
    }


    public void setTime(int parameterIndex, Time x) throws SQLException {
        this._pstmtWrapped.setTime(parameterIndex, x);
    }


    public void setTime(int parameterIndex, Time x, Calendar cal) throws SQLException {
        this._pstmtWrapped.setTime(parameterIndex, x, cal);
    }


    public void setTimestamp(int parameterIndex, Timestamp x) throws SQLException {
        this._pstmtWrapped.setTimestamp(parameterIndex, x);
    }


    public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal) throws SQLException {
        this._pstmtWrapped.setTimestamp(parameterIndex, x, cal);
    }


    public void setURL(int parameterIndex, URL x) throws SQLException {
        this._pstmtWrapped.setURL(parameterIndex, x);
    }


    @Deprecated
    public void setUnicodeStream(int parameterIndex, InputStream x, int length) throws SQLException {
        this._pstmtWrapped.setUnicodeStream(parameterIndex, x, length);
    }


    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return (iface == PreparedStatement.class);
    }


    public <T> T unwrap(Class<T> iface) throws SQLException {
        PreparedStatement preparedStatement = null;
        T wrapped = null;
        if (isWrapperFor(iface))
            preparedStatement = this._pstmtWrapped;
        return (T) preparedStatement;
    }
}